[config]
schemaVersion = "0.0.1"

[package]
namespace = "skytech6"
name = "CrimsonSQL_SoD"
versionNumber = "0.1.0"
description = "Framework for Interfacing MySQL"
websiteUrl = "https://github.com/CrimsonMods/CrimsonSQL/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_IL2CPP = "6.0.698"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["shadows-of-doubt"]
repository = "https://thunderstore.io"
[publish.categories]
shadows-of-doubt = ["libraries"]