[config]
schemaVersion = "0.0.1"

[package]
namespace = "skytech6"
name = "CrimsonSQL"
versionNumber = "0.1.0"
description = "Framework for Interfacing MySQL"
websiteUrl = "https://github.com/CrimsonMods/CrimsonSQL/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["oakveil-update", "1-0-update", "mods", "server"]